#!/usr/bin/python3
#
# This script will generate a temporary directory and add all files
# (current and historic) in that repo into a structure like:
# [tmpdir]/[hash]/[filename]
#
# FIXME: should be merged with dorepo

import os
import subprocess
import tempfile

outdir = tempfile.mkdtemp(prefix="gitkeyfind")

revs = subprocess.check_output(["git", "rev-list", "--all"])
revs = revs.decode().splitlines()
# print(revs)

hashtofn = {}
for rev in revs:
    r = subprocess.check_output(["git", "ls-tree", "-r", rev])
    for l in r.decode().splitlines():
        d = l.split(" ")[2].split("\t")
        fn = d[1].split("/")[-1]
        hashtofn[d[0]] = fn

# print(hashtofn)

objects = subprocess.check_output(
    ["git", "cat-file", "--batch-check", "--batch-all-objects", "--unordered"]
)

blobs = []
for o in objects.decode().splitlines():
    d = o.split(" ")
    if d[1] != "blob":
        continue
    blobs.append(d[0])

for blob in blobs:
    fn = hashtofn[blob]
    os.mkdir(f"{outdir}/{blob}")

    r = subprocess.check_output(["git", "cat-file", "blob", blob])

    with open(f"{outdir}/{blob}/{fn}", "wb") as f:
        f.write(r)

print(outdir)
