---
name: runci
"on":
  - pull_request
  - push

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.9, 3.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }} ${{ matrix.os }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

          pip install black ruff cryptography beautifulsoup4 lxml urllib3 requests
      - name: Run tests
        shell: bash
        run: |
          ./runci.sh
