# last update: 2024-12-06
# https://github.com/hannob/codingstyle
---
name: runpyci
"on":
  - pull_request
  - push

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.9, 3.x, 3.13]  # CUSTOM: not running on 3.14-dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }} ${{ matrix.os }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies and linters
        run: |
          [ -e requirements.txt ] && pip install -r requirements.txt
          pip install pycodestyle pyupgrade pyflakes dlint pylint ruff
          sudo apt-get -y install poppler-utils  # CUSTOM: needed for pdf parsing
      - name: Run tests
        run: |
          ./runpyci.sh
